trigger:
  batch: true
  branches:
    include:
    - master
    exclude:
    - refs/tags/*
pr:
  autoCancel: true
  branches:
    include:
    - master

variables:
- group: codecov
- group: twine

resources:
  containers:
  - container: manylinux
    image: quay.io/pypa/manylinux1_x86_64
  repositories:
  - repository: templates
    type: github
    name: Dish1306/azure-pipelines
    endpoint: aio-libs

stages:
- template: stage-lint.yml
- template: stage-test.yml
  parameters:
    codecov.token: '$(codecov.token)'
- template: templates/stage-aarch64.yml@templates
  parameters:
    step: make cythonize && $PYTHON -m pip install -r requirements/test.txt && \
